### PR TITLE
Prepare for 0.3.0 release

### PR DESCRIPTION
**Pull request by lulf**
@MathiasKoch

### CODE REVIEW

**Review by MathiasKoch — APPROVED** [review]
LGTM :+1: 

Thanks!

**Comment by MathiasKoch** [comment]
Should be available as tag here and on crates.io now :+1:

**Comment by MathiasKoch** [comment]
Is it the correct way to `cargo +nightly publish` for the async one?

**Comment by lulf** [comment]
@MathiasKoch Yes, that is the way. Btw, you need https://github.com/rust-embedded-community/embedded-storage/pull/26 also for cargo publish to work.

**Comment by MathiasKoch** [comment]
Should be live now :+1:

**Comment by lulf** [comment]
@MathiasKoch awesome, thank you for the quick response!

**Pull request merged**
