### PR TITLE
async: Prepare 0.4.0 release

### PR DESCRIPTION
**Pull request by eldruin**
I added a changelog, the licenses and filled the authors in commit order.
Is there anything left to do before the 0.4.0 release?

@MathiasKoch could you add the team @rust-embedded-community/embedded-storage to crates.io?

cc: @lulf, @Dirbaio

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
LGTM, I don't think there's anything else pending!

**Comment by Dirbaio** [comment]
ping @MathiasKoch

**Comment by MathiasKoch** [comment]
Ohh.. sorry, i missed this initially due to my inactivity by paternity leave. 

Will add the team tomorrow morning. 👍

**Comment by MathiasKoch** [comment]
Done :+1:

**Comment by Dirbaio** [comment]
Ping again! @eldruin @MathiasKoch could we get this released? 

I volunteer to be a maintainer, if it helps!

**Comment by eldruin** [comment]
Sorry for the delay. Let's get this released.

**Pull request merged**
